version: 2.1

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3

    working_directory: ~/project

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-gem-cache-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
            - v1-gem-cache-{{ arch }}-{{ .Branch }}-
            - v1-gem-cache-{{ arch }}-

      - run:
          name: install dependencies
          command: |
            gem update --system
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
