version: 2.1

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3

    working_directory: ~/project

    environment:
      BUNDLE_PATH: ~/project/vendor/bundle
      BUNDLER_VERSION: '2.0.2'

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-gem-cache-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
            - v1-gem-cache-{{ arch }}-{{ .Branch }}-
            - v1-gem-cache-{{ arch }}-

      - run: gem install "bundler:${BUNDLER_VERSION}"
      - run: bundle install --jobs=4 --retry=3 --path "${BUNDLE_PATH}"

      - save_cache:
          paths:
            - vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
